import Header from "@/components/layout/header";
import UserProvider from "@/components/providers/user-provider";
import { getCachedUser, getProfile } from "@/db/server/user";
import "@/styles/globals.css";
import { ResultOf } from "@/types/utils";
import type { Metadata } from "next";

import { Roboto } from "next/font/google";
import { FunctionComponent, PropsWithChildren } from "react";
const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700", "900"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Layout: FunctionComponent<PropsWithChildren> = async ({ children }) => {
	const {
		data: { user },
	} = await getCachedUser();

	let profile: ResultOf<typeof getProfile> | null = null;

	if (user) {
		profile = await getProfile(user.id);
	}

	return (
		<html lang="en">
			<body className={`${roboto.className} antialiased`}>
				<UserProvider profile={profile}>
					<Header />
					{children}
				</UserProvider>
			</body>
		</html>
	);
};

export default Layout;
